### ISSUE TITLE
Alternator not logging into account after July 18 update. 

### ISSUE THREAD

**Issue by onilosmada** [SamMackrill/gw2-alternator#184]
I recently noticed that my accounts were logging in and completing way too quickly. Interface/Character Select screen would not load and immediately after the login prompt Alternator would register Complete. When I checked the accounts they were in fact not logging in. I think there are 2 possible culprits. Recently Anet retired a few command line arguments related to coherent UI and dx9 support, and there may be an issue with Kill MUTEX and the new build. I tested the command line theory by go into the fastest GFX.xml and removed the old -dx9 arguments and that didn't seem to solve the problem.

Log files and Crash report below:

[gw2-alternator-metrics_2023-07-26_01-47-23.txt](https://github.com/SamMackrill/gw2-alternator/files/12167164/gw2-alternator-metrics_2023-07-26_01-47-23.txt)
[gw2-alternator-launch-Login-log.20230725.7.txt](https://github.com/SamMackrill/gw2-alternator/files/12167165/gw2-alternator-launch-Login-log.20230725.7.txt)

--> Crash <--
Assertion: No valid case for switch variable 'grInterface'
File: D:\Perforce\Live\NAEU\v2\Code\Arena\Engine\Gr\Windows\GrWindow.cpp(1084)
App: Gw2-64.exe
Pid: 7620
BaseAddr: 00007FF63C910000
ProgramId: 101
Build: 149126
When: 2023-07-26T02:00:02Z 2023-07-25T21:00:02-05:00
Uptime: 0 days 0:00:21
Flags: 0
DumpFile: Crash.dmp

--> System <--
Name: 7881149e
IpAddr: 192.168.86.160
Processors: 4 [GenuineIntel:6:12:3]
OSVersion: Windows 10.0 (64 bit)

--> System Memory <--
Physical: 10478MB/16325MB 64%
Paged: 9799MB/18757MB 52%
Virtual: 134179701MB/134217727MB 3%
Load: 35%
CommitTotal: 8958MB
CommitLimit: 18757MB
CommitPeak: 11952MB
SystemCache: 9104MB
HandleCount: 91512
ProcessCount: 211
ThreadCount: 3133

--> Process Memory <--
Private: 450MB
WorkingSet: 236MB
PeakWorkingSet: 236MB
PageFaults: 601561

--> Memory Category Usage (Inclusive) <--
[Category] [Size(MB)] [Count]
Root 280.72 11168
Programmer Data 221.09 5691
Engine 154.90 213
Gr 154.88 202
DDI 148.89 158
Uncategorized 53.18 4722
I/O 37.98 597
Archive 36.64 38
Collections 27.87 4624
Dictionary 26.10 51
Collide 6.45 755
Collide Havok 6.45 755
File Service 1.24 12
BTree 0.57 36
Networking 0.14 24
Event 0.13 5
Asset Service 0.09 544
Gr Umbra 0.06 2
Game 0.05 55
Content 0.02 1
Threading 0.01 15
Msg 0.01 9
Model-Programmer 0.01 1
Gr Texture 0.01 14

--> Memory Category Usage (Exclusive) <--
[Category] [Size(MB)] [Count]
DDI 148.89 153
Uncategorized 53.18 4722
Archive 36.64 38
Dictionary 26.10 51
Collide Havok 6.45 755
Gr 5.91 27
File Service 1.24 12
Collections 1.21 4536
BTree 0.57 36
Event 0.13 5
Networking 0.12 15
Asset Service 0.09 544
Gr Umbra 0.06 2
Game 0.03 46
Content 0.02 1
Threading 0.01 15
Msg 0.01 9
Model-Programmer 0.01 1
Gr Texture 0.01 14
Engine 0.01 6
Install 0.00 32
Web Browser 0.00 14
Platform 0.00 65
CharClient 0.00 5

--> DllList <--
00007FF63C910000 - X:\Guild Wars 2\Gw2-64.exe
00007FFACF1B0000 - C:\WINDOWS\SYSTEM32\ntdll.dll
00007FFACD860000 - C:\WINDOWS\System32\KERNEL32.DLL
00007FFACC9E0000 - C:\WINDOWS\System32\KERNELBASE.dll
00007FFAC9FD0000 - C:\WINDOWS\SYSTEM32\apphelp.dll
00007FFACEF10000 - C:\WINDOWS\System32\USER32.dll
00007FFACC9B0000 - C:\WINDOWS\System32\win32u.dll
00007FFACD830000 - C:\WINDOWS\System32\GDI32.dll
00007FFACC890000 - C:\WINDOWS\System32\gdi32full.dll
00007FFACCE20000 - C:\WINDOWS\System32\msvcp_win.dll
00007FFACCEC0000 - C:\WINDOWS\System32\ucrtbase.dll
00007FFACD770000 - C:\WINDOWS\System32\ADVAPI32.dll
00007FFACDB70000 - C:\WINDOWS\System32\msvcrt.dll
00007FFACD6D0000 - C:\WINDOWS\System32\sechost.dll
00007FFACD980000 - C:\WINDOWS\System32\RPCRT4.dll
00007FFACE230000 - C:\WINDOWS\System32\WS2_32.dll
00007FFACD1A0000 - C:\WINDOWS\System32\WINTRUST.dll
00007FFACD5A0000 - C:\WINDOWS\System32\ole32.dll
00007FFACE2A0000 - C:\WINDOWS\System32\combase.dll
00007FFACD330000 - C:\WINDOWS\System32\OLEAUT32.dll
00007FFACE7C0000 - C:\WINDOWS\System32\SHELL32.dll
00007FFACCFF0000 - C:\WINDOWS\System32\CRYPT32.dll
00007FFAC7040000 - C:\WINDOWS\SYSTEM32\VERSION.dll
00007FFAC8020000 - C:\WINDOWS\SYSTEM32\WTSAPI32.dll
00007FFABC220000 - C:\WINDOWS\SYSTEM32\WINMM.dll
00007FFA76C00000 - C:\WINDOWS\SYSTEM32\MSACM32.dll
00007FFAB9B30000 - C:\WINDOWS\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.19041.2251_none_91a40448cc8846c1\gdiplus.dll
00007FFABA770000 - C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.1110_none_792d1c772443f647\COMCTL32.dll
00007FFA8AE60000 - C:\WINDOWS\SYSTEM32\USP10.dll
00007FFABBFF0000 - C:\WINDOWS\SYSTEM32\MSIMG32.dll
00007FFAB4E50000 - C:\WINDOWS\SYSTEM32\Secur32.dll
00007FFAA5720000 - C:\WINDOWS\SYSTEM32\winmmbase.dll
00007FFACC240000 - C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
00007FFACC770000 - C:\WINDOWS\SYSTEM32\SSPICLI.DLL
00007FFACD950000 - C:\WINDOWS\System32\IMM32.DLL
00007FFACC460000 - C:\WINDOWS\SYSTEM32\MSASN1.dll
00007FFACCCE0000 - C:\WINDOWS\System32\bcryptPrimitives.dll
00007FFAC3700000 - C:\WINDOWS\SYSTEM32\dbghelp.dll
00007FFACA920000 - C:\WINDOWS\SYSTEM32\windows.storage.dll
00007FFACC2D0000 - C:\WINDOWS\SYSTEM32\Wldp.dll
00007FFACE710000 - C:\WINDOWS\System32\SHCORE.dll
00007FFACF110000 - C:\WINDOWS\System32\shlwapi.dll
00007FFACC7C0000 - C:\WINDOWS\SYSTEM32\profapi.dll
00007FFACB120000 - C:\WINDOWS\SYSTEM32\kernel.appcore.dll
00007FFACCFC0000 - C:\WINDOWS\System32\bcrypt.dll
00007FFACA130000 - C:\WINDOWS\system32\uxtheme.dll
00007FFAC6940000 - C:\WINDOWS\SYSTEM32\cryptnet.dll
00007FFACD930000 - C:\WINDOWS\System32\imagehlp.dll
00007FFACC220000 - C:\WINDOWS\SYSTEM32\CRYPTSP.dll
00007FFACB8E0000 - C:\WINDOWS\system32\rsaenh.dll
00007FFAC7290000 - C:\WINDOWS\SYSTEM32\dxcore.dll
00007FFACD150000 - C:\WINDOWS\System32\cfgmgr32.dll
00007FFAC61A0000 - C:\WINDOWS\SYSTEM32\drvstore.dll
00007FFACC620000 - C:\WINDOWS\SYSTEM32\devobj.dll
00007FFA81E30000 - C:\WINDOWS\system32\nvspcap64.dll
00007FFACBA00000 - C:\WINDOWS\SYSTEM32\ntmarta.dll
00007FFACB0F0000 - C:\WINDOWS\SYSTEM32\gpapi.dll
00007FFA98BC0000 - C:\WINDOWS\SYSTEM32\DINPUT8.dll
00007FFAAEEC0000 - C:\WINDOWS\SYSTEM32\inputhost.dll
00007FFAC9DA0000 - C:\WINDOWS\SYSTEM32\CoreMessaging.dll
00007FFAC7D40000 - C:\WINDOWS\SYSTEM32\PROPSYS.dll
00007FFAC9290000 - C:\WINDOWS\SYSTEM32\wintypes.dll
00007FFAC9A40000 - C:\WINDOWS\SYSTEM32\CoreUIComponents.dll
00007FFACBCD0000 - C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
00007FFACD920000 - C:\WINDOWS\System32\NSI.dll
00007FFAC7070000 - C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
00007FFACDC10000 - C:\WINDOWS\System32\Setupapi.dll
00007FFAC3A80000 - C:\WINDOWS\system32\nvapi64.dll
00007FFACDAB0000 - C:\WINDOWS\System32\clbcatq.dll
00007FFAC7AF0000 - C:\WINDOWS\system32\napinsp.dll
00007FFAB0940000 - C:\WINDOWS\system32\pnrpnsp.dll
00007FFAA8280000 - C:\WINDOWS\system32\wshbth.dll
00007FFAC8FE0000 - C:\WINDOWS\system32\NLAapi.dll
00007FFACC030000 - C:\WINDOWS\System32\mswsock.dll
00007FFACBD20000 - C:\WINDOWS\SYSTEM32\DNSAPI.dll
00007FFAB02F0000 - C:\WINDOWS\System32\winrnr.dll
00007FFABC130000 - C:\WINDOWS\System32\fwpuclnt.dll
00007FFABC250000 - C:\Windows\System32\rasadhlp.dll
00007FFACD210000 - C:\WINDOWS\System32\msctf.dll
00007FFAAF220000 - C:\WINDOWS\SYSTEM32\textinputframework.dll
00007FFAC62F0000 - C:\WINDOWS\SYSTEM32\WindowsCodecs.dll
00007FFAAB870000 - C:\WINDOWS\SYSTEM32\TextShaping.dll
00007FFA1B5A0000 - X:\Guild Wars 2\bin64\cef\libcef.dll
00007FFACD4C0000 - C:\WINDOWS\System32\COMDLG32.dll
00007FFACB140000 - C:\WINDOWS\SYSTEM32\dxgi.dll
00007FFA9CFB0000 - C:\WINDOWS\SYSTEM32\UIAutomationCore.DLL
00007FFAB9CE0000 - C:\WINDOWS\SYSTEM32\OLEACC.dll
00007FFACC740000 - C:\WINDOWS\SYSTEM32\USERENV.dll
00007FFAB7610000 - C:\WINDOWS\SYSTEM32\NETAPI32.dll
00007FFACB0E0000 - C:\WINDOWS\SYSTEM32\HID.DLL
00007FFA67920000 - X:\Guild Wars 2\bin64\cef\chrome_elf.dll
00007FFAB8050000 - C:\WINDOWS\SYSTEM32\DWrite.dll
00007FFACA4C0000 - C:\WINDOWS\SYSTEM32\dwmapi.dll
00007FFACC340000 - C:\WINDOWS\SYSTEM32\ncrypt.dll
00007FFAB9D50000 - C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
00007FFAACFA0000 - C:\WINDOWS\SYSTEM32\d3d9.dll
00007FFA82140000 - C:\WINDOWS\SYSTEM32\dxva2.dll
00007FFAB3BB0000 - C:\WINDOWS\SYSTEM32\CRYPTUI.dll
00007FFAB6540000 - C:\WINDOWS\SYSTEM32\urlmon.dll
00007FFAC6090000 - C:\WINDOWS\SYSTEM32\WINHTTP.dll
00007FFA800F0000 - C:\WINDOWS\SYSTEM32\credui.dll
00007FFAC74D0000 - C:\WINDOWS\SYSTEM32\wevtapi.dll
00007FFAADCD0000 - C:\WINDOWS\SYSTEM32\WININET.dll
00007FFABBC90000 - C:\WINDOWS\SYSTEM32\ESENT.dll
00007FFAB5F10000 - C:\WINDOWS\SYSTEM32\iertutil.dll
00007FFAB6750000 - C:\WINDOWS\SYSTEM32\srvcli.dll
00007FFACBD10000 - C:\WINDOWS\SYSTEM32\netutils.dll
00007FFAC8340000 - C:\WINDOWS\SYSTEM32\DSROLE.DLL
00007FFACBA40000 - C:\WINDOWS\SYSTEM32\WKSCLI.DLL
00007FFAC4580000 - C:\WINDOWS\SYSTEM32\SAMCLI.DLL
00007FFACC300000 - C:\WINDOWS\SYSTEM32\NTASN1.dll
00007FFACC660000 - C:\WINDOWS\SYSTEM32\DPAPI.dll
00007FFAC6C90000 - C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
00007FFACB580000 - C:\WINDOWS\SYSTEM32\WINSTA.dll
00007FFAC5650000 - C:\WINDOWS\System32\MMDevApi.dll
00007FFAC5D40000 - C:\WINDOWS\SYSTEM32\mscms.dll
00007FFAC5DF0000 - C:\WINDOWS\SYSTEM32\ColorAdapterClient.dll
00007FFAC81F0000 - C:\WINDOWS\SYSTEM32\DSREG.DLL
00007FFACB970000 - C:\WINDOWS\SYSTEM32\msvcp110_win.dll
00007FFACBE40000 - C:\WINDOWS\SYSTEM32\POWRPROF.dll
00007FFACBCB0000 - C:\WINDOWS\SYSTEM32\UMPDC.dll
00007FFAA2C10000 - C:\Users\Ali\AppData\Local\Temp\CB850469-1ED1-4DD2-B77D-78C36FF610B9\amd_ags_x64.dll
00007FFAB69D0000 - C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll
00007FFAC8350000 - C:\WINDOWS\SYSTEM32\d3d11.dll
00007FFAC2C00000 - C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_675be35f1ba2315e\nvldumdx.dll
00007FFABC300000 - C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_675be35f1ba2315e\nvwgf2umx.dll
00007FFA65670000 - C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_675be35f1ba2315e\NvCamera\NvCamera64.dll
00007FFAA1930000 - C:\WINDOWS\SYSTEM32\XINPUT9_1_0.dll
00007FFAAF320000 - C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_675be35f1ba2315e\Display.NvContainer\MessageBus.dll
00007FFA65260000 - C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_675be35f1ba2315e\NvCamera\d3dcompiler_47_64.dll
00007FFAC93F0000 - C:\WINDOWS\SYSTEM32\dcomp.dll

--> Game Context <--
MapId: 0
Flags: 0x241
ElapsedTime: 00:00:20

--> World State <--

[DbgHelp.dll is C:\WINDOWS\SYSTEM32\dbghelp.dll]
[DbgHelp.dll version 10.0.19041.867 (64/32-bit compatible)]

--> ClientContextThreadProc Thread 0x2fe0 <--

--> Trace <--
Pc Rt : Args
00007ff63c9cffb5 0000000000000000 : 0000000000000000 0000000000000000 0000000000000000 0000000000000000
00007ff63caaff01 0000000000000000 : 0000000000000000 0000000000000000 0000000000000000 0000000000000000
00007ff63caec95c 0000000000000000 : 0000000000000000 0000000000000000 0000000000000000 0000000000000000
00007ff63c9d5bed 0000000000000000 : 0000000000000000 0000000000000000 0000000000000000 0000000000000000
00007ff63d42610b 0000000000000000 : 0000000000000000 0000000000000000 0000000000000000 0000000000000000
00007ff63cd889b6 0000000000000000 : 0000000000000000 0000000000000000 0000000000000000 0000000000000000
00007ff63cd805fb 0000000000000000 : 0000000000000000 0000000000000000 0000000000000000 0000000000000000
00007ff63c9ac262 0000000000000000 : 0000000000000000 0000000000000000 0000000000000000 0000000000000000
00007ff63cc3956c 0000000000000000 : 0000000000000000 0000000000000000 0000000000000000 0000000000000000
00007ff63cc37b00 0000000000000000 : 0000000000000000 0000000000000000 0000000000000000 0000000000000000
00007ff63cc3776d 0000000000000000 : 0000000000000000 0000000000000000 0000000000000000 0000000000000000
00007ff63cc38af7 0000000000000000 : 0000000000000000 0000000000000000 0000000000000000 0000000000000000
00007ff63cc38bc6 0000000000000000 : 0000000000000000 0000000000000000 0000000000000000 0000000000000000
00007ff63cc36ed5 0000000000000000 : 0000000000000000 0000000000000000 0000000000000000 0000000000000000
00007ff63c9c6279 0000000000000000 : 0000000000000000 0000000000000000 0000000000000000 0000000000000000
00007ff63cbf075a 0000000000000000 : 0000000000000000 0000000000000000 0000000000000000 0000000000000000
00007ffacd877614 0000000000000000 : 0000000000000000 0000000000000000 0000000000000000 0000000000000000
00007ffacf2026b1 0000000000000000 : 0000000000000000 0000000000000000 0000000000000000 0000000000000000

--> Thread registers <--
rax=0000000000000001 rbx=00007ff63e133780 rcx=0000009f71afee10
rdx=0000000000000200 rsi=000001bc5ac78440 rdi=000000000000043c
rip=00007ff63c9cff51 rsp=0000009f71afedb0 rbp=0000009f71aff619
r8=000000000000002f r9=00007ff63e133800 r10=0000000000000017
r11=0000009f71aff508 r12=0000000000000000 r13=00007ff63eb8db60
r14=00000000ffffffff r15=0000000000000002
cs=0033 ss=002b ds=002b es=002b fs=0053 gs=002b efl=00000202

rbx-32 00007FF63E133760 000000003f800000 3f80000000000000 bf800000bf800000 bf800000bf800000
rbx +0 00007FF63E133780 6f667265505c3a44 6576694c5c656372 32765c5545414e5c 72415c65646f435c
rbx+32 00007FF63E1337A0 69676e455c616e65 69575c72475c656e 72475c73776f646e 632e776f646e6957
rcx-32 0000009F71AFEDF0 0000009f71aff528 00007ff63c9cff51 0000009f71afedb0 0000009f71aff619
rcx +0 0000009F71AFEE10 0000000000000000 0000000000000001 000001bc67f549b0 00007ffacf1db86b
rcx+32 0000009F71AFEE30 0000000000000000 000000000000037f 00009fa00010000f 0053002b002b0033
r9-32 00007FF63E1337E0 646e69575f72475f 7373616c435f776f 0000000000000000 006e006500720041
r9 +0 00007FF63E133800 00740065004e0061 005f00720047005f 0064006e00690057 0043005f0077006f
r9+32 00007FF63E133820 007300730061006c 0000000000000000 73616c43204d4f4d 0000000000000073

--> Code <--
00007ff63c9cff31  8d4c2440 e8a685fe ff488d0d ef1a2802 .L$@.....H....(. 00007ff63c9cff41 e85a0efe ff488d4c 2460ff15 cf335801 .Z...H.L$...3X. 00007ff63c9cff51 488b8424 58010000 4c8d05d0 65590148 H..$X...L...eY.H
00007ff63c9cff61  89442448 488d9424 30050000 488b8424 .D$HH..$0...H..$ 00007ff63c9cff71 f8000000 4885db48 89442450 448bcf48 ....H..H.D$PD..H
00007ff6`3c9cff81 8b842400 0100004c 0f45c348 89442458 ..$....L.E.H.D$X

--> Stack <--
0000009f71afedb0  00007ff63e133780 00007ffacf1ddc91 000001bc52190000 0000009f71aff0b9 .7.>...............R.......q.... 0000009f71afedd0 0000009f71afedf8 0000009f71afee10 0000000000000000 0000000000002161 ...q.......q............a!......
0000009f71afedf0  0000009f71aff528 00007ff63c9cff51 0000009f71afedb0 0000009f71aff619 (..q....Q..<.......q.......q.... 0000009f71afee10 0000000000000000 0000000000000001 000001bc67f549b0 00007ffacf1db86b .................I.g....k.......
0000009f71afee30  0000000000000000 000000000000037f 00009fa00010000f 0053002b002b0033 ........................3.+.+.S. 0000009f71afee50 00000202002b002b 0000000000000000 000001bc67f549b0 000001bc52130d80 +.+..............I.g.......R....
0000009f71afee70  0000000000000160 000001bc52130000 000001bc521302a8 0000000000000001 ..........R.......R............
0000009f71afee90  0000009f71afee10 0000000000000200 00007ff63e133780 0000009f71afedb0 ...q.............7.>.......q.... 0000009f71afeeb0 0000009f71aff619 000001bc5ac78440 000000000000043c 000000000000002f ...q....@..Z....<......./.......
0000009f71afeed0  00007ff63e133800 0000000000000017 0000009f71aff508 0000000000000000 .8.>...............q............ 0000009f71afeef0 00007ff63eb8db60 00000000ffffffff 0000000000000002 00007ff63c9cff51 ..>....................Q..<.... 0000009f71afef10 000000000000027f 0000000000000000 0000000000000000 0000ffff00009fa0 ................................
0000009f71afef30  0000000000000000 0000000000000000 0000000000000000 0000000000000000 ................................ 0000009f71afef50 0000000000000000 0000000000000000 0000000000000000 0000000000000000 ................................
0000009f71afef70  0000000000000000 0000000000000000 0000000000000000 0000000000000000 ................................ 0000009f71afef90 0000000000000000 0000000000000000 0000000000000000 0000000000000000 ................................
0000009f71afefb0  0000000000000000 0000000000000000 0000000000000000 0000000000000000 ................................ 0000009f71afefd0 0000000000000000 0000000000000000 0000000000000000 0000000000000000 ................................
0000009f71afeff0  0000000000000000 0000000000000000 0000000000000000 0000000000000000 ................................ 0000009f71aff010 0000000000000000 0000000000000000 0000000000000000 0000000000000000 ................................
0000009f71aff030  0000000000000000 0000000000000000 0000000000000000 0000000000000000 ................................ 0000009f71aff050 0000000000000000 0000000000000000 0000000000000000 0000000000000000 ................................
0000009f71aff070  0000000000000000 0000000000000000 0000000000000000 0000000000000000 ................................ 0000009f71aff090 0000000000000000 0000000000000000 0000000000000000 0000000000000000 ................................
0000009f71aff0b0  0000000000000000 0000000000000001 000001bc67ceded0 00007ff63cadf2d0 ...................g.......<.... 0000009f71aff0d0 0000000000000000 00000000000000e0 000001bc52190150 0000000000000000 ................P..R............
0000009f71aff0f0  0000000000000091 00000000000003ff 000001bc67ceded0 000001bc52190000 ...................g.......R.... 0000009f71aff110 0000000000000111 00007ffacf1cf47e 000001bc67f549c0 00007ffacf1ba46c ........~........I.g....l.......
0000009f71aff130  0000000000003b47 00000000000003ff 000001bc5c03e550 0000000000000111 G;..............P..\............ 0000009f71aff150 0000000000000007 000001bc52190150 0d1cef1600000000 00000000000003ff ........P..R....................
0000009f71aff170  0000000000000000 000000002fbeba64 000001bc5219b814 0000000000000111 ........d../.......R............ 0000009f71aff190 0000000000000000 00007ffacf1d0b31 000001bc54357fb0 0000000000020020 ........1.........5T.... .......

--> Error Logs <--
01:59:57Z Failed to write user-preferences.
02:00:02Z The user closed the browser.
02:00:02Z The browser is being closed.
02:00:02Z We are requesting CEF close the browser when the user closed the browser.
02:00:02Z The user closed the browser.
02:00:02Z CEF is closing the browser.
Crashed at 02:00:02Z

--> Graphics Device Info <--
VendorId = 0x10de
DeviceId = 0x1401
Version = 53623
Description = NVIDIA GeForce GTX 960
Compat = 0x000000001f77fc3f
VidMem = 4096 MB

--> NVidia Info <--
DriverVersion = 536.23

**Comment by SamMackrill** [comment]
Odd, I have been using it every day since the patch. So it seems like GW2 is immediately crashing when launched via alternator. Did the update task also fail?

**Comment by SamMackrill** [comment]
I was in the process of creating a login analyser that can help diagnose this. However it seems likely that arenanet will be redoing daily rewards in the next expansion. Bit reluctant to spend more time here until we know more

**Comment by SamMackrill** [comment]
It is possible that I am not seeing an issue because I am running my dev version, I will try and check

**Comment by SamMackrill** [comment]
GW2-Aternator Version: 1.0.26
This version is nearly a year old! try updating

**Comment by onilosmada** [comment]
Oops, yep that was it. I had multiple versions on my computer and apparently i was using the wrong one. 
Thanks Bro!
Brilliant piece of software.
