### ISSUE TITLE
Scrolling breaks selection

### ISSUE THREAD

**Issue by Andunes** [SamMackrill/gw2-alternator#81]
Scrolling the list of accounts before selecting a specific account to launch seems to ignore the selection. Selecting and launching without scrolling or using the column headers to sort works as expected.

For example, let say I have 20 accounts and want to collect account 2 I can select it and launch as expected. If I want to collect account 18 which requires scrolling, the selection will be ignored.

**Comment by SamMackrill** [comment]
Confirmed, this is totally bizarre.

**Comment by SamMackrill** [comment]
Ah https://stackoverflow.com/questions/23441113/why-is-the-datagridrow-isselected-binding-not-working-on-datagrid/72927271#72927271
