### ISSUE TITLE
Stuck After Logging In

### ISSUE THREAD

**Issue by twolve** [SamMackrill/gw2-alternator#96]
After recent GW2 updates, the log in seems to fail more often. Sometimes this happens a lot or not at all. It will log into the account fine, but it will never hit play and get past the launcher even after attempting that account multiple times.

**Comment by SamMackrill** [comment]
Yeah, I noticed this too, working on a fix

**Comment by Caliban2017** [comment]
Noticed the same Problem. After the latest Update from tonight, the automatic Login is completely broken. I must click Sign In manually on every Account.

**Comment by SamMackrill** [comment]
Try the latest and let me know: https://github.com/SamMackrill/gw2-alternator/releases/tag/V1.0.26

**Comment by Caliban2017** [comment]
I will try it on my Daily Reset, thanks for your Work! Launch Buddy seems be buggy too... a completly mess.

**Comment by twolve** [comment]
Heya! I gave it a shot this morning, and it worked wonderfully. You're fantastic. :)
